



set_property IOSTANDARD LVCMOS33 [get_ports {bcd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bcd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bcd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bcd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[0]}]


set_property PACKAGE_PIN U9 [get_ports {bcd[0]}]
set_property PACKAGE_PIN U8 [get_ports {bcd[1]}]
set_property PACKAGE_PIN R7 [get_ports {bcd[2]}]
set_property PACKAGE_PIN R6 [get_ports {bcd[3]}]
set_property PACKAGE_PIN L3 [get_ports {out[0]}]
set_property PACKAGE_PIN N1 [get_ports {out[1]}]
set_property PACKAGE_PIN L5 [get_ports {out[2]}]
set_property PACKAGE_PIN L4 [get_ports {out[3]}]
set_property PACKAGE_PIN K3 [get_ports {out[4]}]
set_property PACKAGE_PIN M2 [get_ports {out[5]}]
set_property PACKAGE_PIN L6 [get_ports {out[6]}]
set_property PACKAGE_PIN M4 [get_ports {out[7]}]


set_property IOSTANDARD LVCMOS33 [get_ports {sel[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports {out_sel[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_sel[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_sel[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_sel[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_sel[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_sel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_sel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_sel[0]}]
set_property PACKAGE_PIN M1 [get_ports {out_sel[7]}]
set_property PACKAGE_PIN N6 [get_ports {out_sel[0]}]
set_property PACKAGE_PIN M6 [get_ports {out_sel[1]}]
set_property PACKAGE_PIN M3 [get_ports {out_sel[2]}]
set_property PACKAGE_PIN N5 [get_ports {out_sel[3]}]
set_property PACKAGE_PIN N2 [get_ports {out_sel[4]}]
set_property PACKAGE_PIN N4 [get_ports {out_sel[5]}]
set_property PACKAGE_PIN L1 [get_ports {out_sel[6]}]
set_property PACKAGE_PIN P4 [get_ports {sel[7]}]
set_property PACKAGE_PIN P3 [get_ports {sel[6]}]
set_property PACKAGE_PIN R3 [get_ports {sel[5]}]
set_property PACKAGE_PIN T1 [get_ports {sel[4]}]
set_property PACKAGE_PIN T3 [get_ports {sel[3]}]
set_property PACKAGE_PIN U2 [get_ports {sel[2]}]
set_property PACKAGE_PIN V2 [get_ports {sel[1]}]
set_property PACKAGE_PIN U4 [get_ports {sel[0]}]
