set_property PACKAGE_PIN U9 [get_ports a]
set_property PACKAGE_PIN U8 [get_ports b]
set_property PACKAGE_PIN R7 [get_ports sel]
set_property PACKAGE_PIN T6 [get_ports y]
set_property IOSTANDARD LVCMOS33 [get_ports a]
set_property IOSTANDARD LVCMOS33 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports sel]
set_property IOSTANDARD LVCMOS33 [get_ports y]
